-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgBwGVuyjeXCgEIUuB
cz0fgAztV7iSQ8/VGKDyac5XnfWgCgYIKoZIzj0DAQehRANCAAQMQgSZGcJD4urA
fRK7DE96vaJmVfigfaTPeYL3e5NCCk7Aux0aVVSDIe72eTSLslgF88BjvMTvrHv9
jGkxAB7Y
-----END PRIVATE KEY-----